### ISSUE TITLE
Selfdestruct ship in a fleet

### ISSUE THREAD

**Issue by Skratti** [Skratti/EmpiresInSpace#146] opened 2016-10-05 07:58 UTC
Fleet keeps a ship - Ship shouldn't be shown anymore...

**Comment by Cerphon** [comment] 2021-02-03 17:10
I am unable to reproduce this.
The number of ships after one is self-destructed is correct and the fleet is disbanded if there is only one left.
Even if I move a ship onto a field with another ship, so that both sprite are shown, one vanishes if the corresponding ship is destroyed from that fleet.
The types of the different ships also do not matter. If the last ship of the type shown as the "flagship" is destroyed, another ships type sprite is shown.

I believe this issue was already resolved in a previous change.

**Closed** 2021-02-04 10:29 UTC
Labels: bug
