### ISSUE TITLE
View Occupied Planets

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#107] opened 2016-09-16 13:36 UTC
when a fleet is hovering over a opponents planet, I think it should be possible to see that is on the planet (buildings/production/population)

**Comment by Skratti** [comment] 2017-03-02 17:29
Duplicate of https://github.com/Skratti/EmpiresInSpace/issues/91

**Closed by Skratti** 2017-03-02 17:29 UTC
