### ISSUE TITLE
Transfer Dialog: miss click closes dialog

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#154] opened 2016-10-08 13:39 UTC
If you don't click on a module, but slightly next to it onto the gray panel, the dialog closes. This is annoying as it can happen quite easily if doing things quick. Clicking the gray panel should not close the dialog.

**Comment by Cerphon** [comment] 2021-02-03 15:29
Reproduce:
Transfer goods from ship or station, click on grey panel (does not happen when transferred from planet to ship/station)

**Comment by Cerphon** [comment] 2021-02-04 11:39
This bug stems from a ship being deselected if one clicks somewhere else than a button.
The whole dialog opened by the transfer is an exception to this.

I propose the following three solutions:

1. Adding the cargo panel of the selected ship to the exception made for the transfer dialog.
2. Not deselecting a ship when its description panel is clicked.
3. Not deselecting a ship when it is not necessitated.

**Comment by Cerphon** [comment] 2021-03-18 13:43
Now the dragging and clicking functions as intended.

**Closed by Cerphon** 2021-03-18 13:43 UTC
Labels: bug
